# Generated by Django 5.2.7 on 2025-12-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='questions_a_created_ac1045_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_q_created_d1d888_idx',
        ),
    ]
