# Generated by Django 5.2.7 on 2025-12-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_answer_questions_a_created_ac1045_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='questions/covers/', verbose_name='Обложка'),
        ),
    ]
