"""
Django settings for StackOverflow project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from configparser import ConfigParser

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

config = ConfigParser()
config.read(os.path.join(BASE_DIR, 'conf', 'django.conf'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get('project', 'SECRET_KEY', raw=True, fallback='<UNFILLED_SECRET_KEY>')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'questions',
    'centrifuge'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE += [
    'users.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'StackOverflow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StackOverflow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # },
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "stackoverflow_db",
        "USER": "stackoverflow_user",
        "PASSWORD": "password",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

LOGIN_REDIRECT_URL = "users:profile"
LOGIN_URL = "users:login"
LOGOUT_REDIRECT_URL = "users:login"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR /"static"]

STATIC_ROOT = BASE_DIR / "staticfiles"

WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": ["redis://localhost:6379/1",],
        "TIMEOUT": config.getint('redis', 'LIFETIME', fallback=9660),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": config.get('redis', 'PREFIX', fallback="StackOverflow"),
    }
}


# Centrifugo

CENTRIFUGE_HOST = config.get('centrifuge', 'HOST', fallback='http://localhost:8035')
CENTRIFUGE_URL = config.get('centrifuge', 'URL', fallback='/centrifuge')
CENTRIFUGE_API_KEY = config.get('centrifuge', 'API_KEY', fallback='')
CENTRIFUGE_SECRET = config.get('centrifuge', 'SECRET', fallback='')
CENTRIFUGE_TOKEN_EXPIRE = config.getint('centrifuge', 'TOKEN_EXPIRE', fallback=120 * 60)
CENTRIFUGE_TIMEOUT = config.getint('centrifuge', 'TIMEOUT', fallback=1)
CENTRIFUGE_ENABLED = config.getboolean('centrifuge', 'ENABLED', fallback=False)

# Mailing

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config.get('smtp', 'HOST', fallback='127.0.0.1')
EMAIL_PORT = config.getint('smtp', 'PORT', fallback=1025)
SENDER_EMAIL = config.get('smtp', 'SENDER_EMAIL')
SERVER_EMAIL = SENDER_EMAIL
UNSUBSCRIBE_TOKEN = config.get('smtp', 'UNSUBSCRIBE_TOKEN', fallback='!SECRET_TOKEN!')
USE_TLS = False


try:
    from .local_settings import *
except ImportError:
    pass